### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by dac0ug** [dunod-docker/application-multi-conteneurs#1]
Hello,

pour info, le build ne s'executait pas chez moi.
Il plantait lors de l'install de la base mariadb:

RUN /usr/bin/mysql_install_db > /dev/null && chown -R mysql:mysql /var/lib/mysql

Pour y remédier, l faut modifier le Dockerfile en ajoutant "--force" à la commande

RUN /usr/bin/mysql_install_db **--force** > /dev/null && chown -R mysql:mysql /var/lib/mysql

**Comment by tgarlot** [comment]
Merci pour cette issue.

Je reproduis effectivement le problème. En remplaçant la commande ci-dessus par `RUN /usr/bin/mysql_install_db` j'ai l'erreur ci-dessous qui confirme bien l'utiliation de la l'option `--force`.

```
Neither host '26be3dcd2d4d' nor 'localhost' could be looked up with
'/usr/libexec/resolveip'
Please configure the 'hostname' command to return a correct
hostname.
If you want to solve this at a later stage, restart this script
with the --force option

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
The command '/bin/sh -c /usr/bin/mysql_install_db' returned a non-zero code: 1
```

Je vais corriger le Dockerfile
