### ISSUE TITLE
symfony install

### ISSUE THREAD

**Issue by dac0ug** [dunod-docker/application-multi-conteneurs#2]
l'install de symfony dans le conteneur ne fonctionne pas avec la commande fournie:

docker exec -i --user=apache lemp /bin/bash -c 'cd /var/www/; symfony new my_app 2.8'

il faut indiquer la bonne version:

docker exec -i --user=apache lemp /bin/bash -c 'cd /var/www/; symfony new my_app 2.8.2'

**Comment by tgarlot** [comment]
Cela semble être un soucis du côté de Symfony...

Ne pas spécifier la version mineure devrait installer la dernière (dans notre cas la 2.8.52) mais cela ne fonctionne effectivement pas dans ce cas. 

```
Downloading Symfony...

  [RuntimeException]
  The selected version (2.8.52) cannot be installed because it does not exist.
  Execute the following command to install the latest stable Symfony release:
  /usr/local/bin/symfony new my-app
```
J'ai essayé avec plusieurs autres versions mineures et le résultat est .... plutôt aléatoire. La version 2.8.2 fonctionne effectivement. 

Il faut donc bien remplacer la commande 
`docker exec -i --user=apache lemp /bin/bash -c 'cd /var/www/; symfony new my_app 2.8'`
par 
`docker exec -i --user=apache lemp /bin/bash -c 'cd /var/www/; symfony new my_app 2.8.2'`

PS: la version de Symfony 2.8 est TRES vieille, de l'époque de la 1ère édition du livre. Actuellement Symfony est à la version 5 mais pour s'assurer que les exemples du reste du chapitre fonctionnent, il est plus prudent de rester sur cette version 2.8.
